still has issues bruh
the error still occurs, the issue just got moved onto different levels

NullReferenceException: Object reference not set to an instance of an object
playermovescript.Update () (at Assets/playermovescript.cs:58)